# @package _global_
architecture:
  hidden_size: 128
  num_gen_hidden_layers: 12
  gen_intermediate_size: 768
  num_disc_hidden_layers: 12
  disc_intermediate_size: 768
  num_attention_heads: 12
  activation: 'gelu'
